version: "3"
services:
  lab:

    container_name: owid_container

    build:
        context: .
        dockerfile: ./Dockerfile

    ports:
      - "8888:8888"

    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    user: 0:0

    volumes:
      - .:/workdir

    command: start.sh jupyter lab



